### ISSUE TITLE
[Refactor] Proper numpy usage

### ISSUE THREAD

**Issue by Pk13055** [akshatcx/jectpack-joyride#1]
Currently, `numpy` is being used in a very non-numpy design. For example, [this](https://github.com/akshatcx/jectpack-joyride/blob/master/arena.py#L15) line can be better written as
```python
board = np.zeros((HEIGHT, WIDTH))
board[56:64, :] = 6
```

**Comment by zjesko** [comment]
Fixed by 13304019d6b66b77d19fedd7b7b18df128495191
